all: devio.exe

publish: P:\Utils\devio.exe

P:\Utils\devio.exe: devio.exe
	copy /y devio.exe P:\Utils\\

devio.exe: devio.c ..\inc\*.h safeio.c safeio.h Makefile.win32
	cl /WX /W4 /Ox /GFS- /GR- /MD /nologo devio.c safeio_win32.cpp /link /defaultlib:wsock32.lib /defaultlib:user32.lib /opt:ref,nowin98,icf=10 /release /nologo /WX
	del *.obj
