#define IMDISK_RC_VERSION_STR    "1.8.6"
#define IMDISK_MAJOR_VERSION     1
#define IMDISK_MINOR_VERSION     8
#define IMDISK_MINOR_LOW_VERSION 6

#define IMDISK_RC_VERSION_FLD IMDISK_MAJOR_VERSION,IMDISK_MINOR_VERSION,IMDISK_MINOR_LOW_VERSION
