EXTERN_C VOID
DoEvents(HWND hWnd);

EXTERN_C INT_PTR CALLBACK
StatusDlgProc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam);

EXTERN_C INT_PTR CALLBACK
NewDlgProc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam);
